### ISSUE TITLE
Command line args

### ISSUE THREAD

**Issue by mattRedBox** [spikelynch/rb2-migrate#7]
Hi
When I run:
`node src/migrate.js --source Test1_9 --dest Test2_0 --type dmpt --outdir ./report`

I get:

```
usage: migrate.js [-h] [-v] [-f FILE] [-s SOURCE] [-d DEST] [-o OUTDIR]
                  [-n NUMBER] [-p PUBLISH]
migrate.js: error: Unrecognized arguments: --type dmpt
```

Is the documentation not quite up-to-date with the working code?

**Comment by mattRedBox** [comment]
From the usage/help, should it now be [-f FILE] ?

**Comment by mattRedBox** [comment]
FILE seems to work just fine, so presuming the README.md just needs an update.

**Comment by spikelynch** [comment]
Yes, you're right, the README.md is out of sync with the script.

We've been busy over the last couple of weeks getting our production redbox data migrated, and most of those changes have been on the migration-fixes branch. We'll be bringing most of these back to master soon.

**Comment by mattRedBox** [comment]
Ok ta
Might compare to the bleeding-edge then and use that in the meantime
